feat: read_tunnel_configuration by yaml file
cargo build
   Compiling copying v0.1.0 (/Users/kazukihigashiguchi/src/github.com/hgsgtk/rust-snippets/httptunnel/copying)
error[E0063]: missing fields `client_connection` and `target_connection` in initializer of `TunnelConfig`
   --> src/configuration.rs:233:21
    |
233 |             None => TunnelConfig{},
    |                     ^^^^^^^^^^^^ missing `client_connection` and `target_connection`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
error: could not compile `copying`

To learn more, run the command again with --verbose.